version: '2'
services:
  web:
    build: .
    volumes:
      - .:/src/repo
      - .bundle:/src/gems/
      - ./keys:/root/.ssh/
    volumes_from:
      - bundle_cache
    ports:
      - '3000:3000'

  bundle_cache:
    image: busybox
    volumes:
      - /src/gems
